### ISSUE TITLE
Adafruit SAMD platform is out of date

### ISSUE THREAD

**Issue by tgvarik** [platformio/platformio-pkg-framework-arduinosam#8]
The Adafruit SAMD platform is now on [v1.2.9](https://github.com/adafruit/ArduinoCore-samd/blob/3f7a027cf1a784c8650307f38790a2f75b3372c6/platform.txt#L23), while this package is stuck on [v1.2.3](https://github.com/platformio/platformio-pkg-framework-arduinosam/blob/cf28026aef2f65e2ddc5c631d2b01a144ff0a068/platform_adafruit.txt#L23). What needs to be done to update?

**Comment by ivankravets** [comment]
Please re-test with upstream version https://docs.platformio.org/en/latest/platforms/atmelsam.html#upstream
